### ISSUE TITLE
Implement GitLab API V4

### ISSUE THREAD

**Issue by splattael** [neopoly/neoboard#18]
Just a reminder, that GitLab's API will change in GitLab `9.3` (~ August 2017) from V3 to V4.

There is a migration doc available at:
https://docs.gitlab.com/ce/api/v3_to_v4.html

I did not look into details yet so maybe we are lucky and don't have to change anything.

/cc @jnbt

**Comment by jnbt** [comment]
Looks like none of the used API calls are changed.

**Comment by splattael** [comment]
Ok, great. Thank you for looking it up :+1: 

So, the only we have to adjust is just the endpoint at https://github.com/neopoly/neoboard/blob/master/config/widgets.exs#L22 ?

**Comment by jnbt** [comment]
As updating our GitLab instance and changing the API to v4 has broken the Widget we need to update the adapter.

**Comment by jnbt** [comment]
Updated in #24
